### PR TITLE
fix axes don't match array error

### PR DESCRIPTION
**Pull request by qizhen816**
fix [#119](https://github.com/triple-Mu/YOLOv8-TensorRT/issues/119)
 
- modified the instance mask generating logic
- modified the segmentation post process logic
- adjust the configs and color formats accordingly

### CODE REVIEW

**Comment by qizhen816** [comment]
I'll test the torch version script and reopen this PR

**Comment by triple-Mu** [comment]
> I'll test the torch version script and reopen this PR

Could you please give me a picture and onnx for reproduce this bug?

**Comment by qizhen816** [comment]
I may not give you the onnx due to company policy, nut you can reproduce it by using any ONNX and an empty image (make sure there is no detection) and run [infer-seg-without-torch.py](https://github.com/triple-Mu/YOLOv8-TensorRT/blob/main/infer-seg-without-torch.py).

**Comment by qizhen816** [comment]
or set --conf-thres=1.0

**Comment by triple-Mu** [comment]
Now fix.

**Pull request closed without merging**
